// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"

/**
 * Generator object for metamagic behavior data std::functions; the function signature will be generated by template params given by the agents responsible for creating a given descriptor, so we can tailor the functors to have whatever I/O params we need.
 */
class RYDDELMYST_API MetamagicDescriptor
{
	std::function<typename... ReturnTypes(typename... ParamTypes)> fn;
public:
	template<typename... ReturnTypes> GenerateBehavior(typename... ParamTypes)
};
